import { NextRequest, NextResponse } from "next/server";
import ical from "ical-generator";
import { addMinutes } from "date-fns";

import { GENERIC_STUDY_SESSION_NAME } from "@/lib/planning";
import prisma from "@/lib/prisma";

export const dynamic = "force-dynamic";

function normalizeStart(date: Date) {
  const value = new Date(date);

  if (value.getHours() === 0 && value.getMinutes() === 0) {
    value.setHours(9, 0, 0, 0);
  }

  return value;
}

function buildSessionDescription(input: {
  courseName: string;
  examName: string;
  topicName: string;
  sessionType: string;
  plannedHours: number;
}) {
  return [
    `Course: ${input.courseName}`,
    `Exam: ${input.examName}`,
    `Topic: ${input.topicName}`,
    `Type: ${input.sessionType}`,
    `Planned hours: ${input.plannedHours.toFixed(2)}h`,
    "Source: StudyScheduler spaced repetition engine",
  ].join("\\n");
}

export async function GET(
  _request: NextRequest,
  context: { params: Promise<{ secret_token: string }> },
) {
  try {
    const { secret_token } = await context.params;

    const user = await prisma.user.findUnique({
      where: {
        calendar_feed_token: secret_token,
      },
      select: {
        id: true,
        name: true,
      },
    });

    if (!user) {
      return NextResponse.json({ error: "Feed not found" }, { status: 404 });
    }

    const now = new Date();

    const sessions = await prisma.studySession.findMany({
      where: {
        exam: {
          userId: user.id,
          status: "ACTIVE",
        },
        planned_date: {
          gte: now,
        },
      },
      include: {
        exam: {
          select: {
            name: true,
            course: {
              select: {
                name: true,
              },
            },
          },
        },
        topic: {
          select: {
            name: true,
          },
        },
      },
      orderBy: {
        planned_date: "asc",
      },
      take: 1000,
    });

    const calendar = ical({
      name: `${user.name ?? "Student"} - StudyScheduler Feed`,
      prodId: {
        company: "StudyScheduler",
        product: "Smart Study Planner",
        language: "EN",
      },
      timezone: "Europe/Rome",
    });

    calendar.description("Read-only feed generated by StudyScheduler");

    for (const session of sessions) {
      const start = normalizeStart(new Date(session.planned_date));
      const durationMinutes = Math.max(
        30,
        Math.round(Math.max(session.planned_hours, 0.5) * 60),
      );
      const end = addMinutes(start, durationMinutes);
      const topicName = session.is_placeholder
        ? GENERIC_STUDY_SESSION_NAME
        : (session.topic?.name ?? "General Review");
      const courseName = session.exam.course?.name ?? "Corso non assegnato";

      calendar.createEvent({
        id: session.id,
        start,
        end,
        summary: `${courseName} • ${session.exam.name} - ${topicName}`,
        description: buildSessionDescription({
          courseName,
          examName: session.exam.name,
          topicName,
          sessionType: session.type.replaceAll("_", " "),
          plannedHours: session.planned_hours,
        }),
      });
    }

    return new NextResponse(calendar.toString(), {
      status: 200,
      headers: {
        "Content-Type": "text/calendar; charset=utf-8",
        "Cache-Control": "no-store, max-age=0",
        "Content-Disposition": "inline; filename=studyscheduler-feed.ics",
      },
    });
  } catch (error) {
    console.error("Failed to generate calendar feed:", error);
    return NextResponse.json(
      { error: "Failed to generate calendar feed" },
      { status: 500 },
    );
  }
}
